### ISSUE TITLE
数字信号处理 2019年复习提纲与资料 季薇

### ISSUE THREAD

**Issue by LR1093141031** [NJUPTFreeExams/NJUPT-TE-Free-Exams#1]
[Chapter 6-z transform B.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997109/Chapter.6-z.transform.B.pdf)
[Chapter 7-discrete time system in transform domain-20191120.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997110/Chapter.7-discrete.time.system.in.transform.domain-20191120.pdf)
[Chapter 8-Digital Filter Structrures.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997111/Chapter.8-Digital.Filter.Structrures.pdf)
[Chapter 9.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997112/Chapter.9.pdf)
[Chapter 10-191210.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997113/Chapter.10-191210.pdf)
[Chapter 11-Discrete Fourier Transform Computation.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997114/Chapter.11-Discrete.Fourier.Transform.Computation.pdf)
[DSP_总复习.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997115/DSP_.pdf)
[Chapter 3-Discrete-Time Signals in the Frequency Domain 191008.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997116/Chapter.3-Discrete-Time.Signals.in.the.Frequency.Domain.191008.pdf)s
[Chapter 4-Discrete Time System190310.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997117/Chapter.4-Discrete.Time.System190310.pdf)
[Chapter 4-Discrete Time System191016.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997118/Chapter.4-Discrete.Time.System191016.pdf)
[Chapter 5-Finite-length Discrete TransformB-191021.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997119/Chapter.5-Finite-length.Discrete.TransformB-191021.pdf)

**Comment by Wonz5130** [comment]
> [Chapter 6-z transform B.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997109/Chapter.6-z.transform.B.pdf)
> [Chapter 7-discrete time system in transform domain-20191120.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997110/Chapter.7-discrete.time.system.in.transform.domain-20191120.pdf)
> [Chapter 8-Digital Filter Structrures.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997111/Chapter.8-Digital.Filter.Structrures.pdf)
> [Chapter 9.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997112/Chapter.9.pdf)
> [Chapter 10-191210.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997113/Chapter.10-191210.pdf)
> [Chapter 11-Discrete Fourier Transform Computation.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997114/Chapter.11-Discrete.Fourier.Transform.Computation.pdf)
> [DSP_总复习.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997115/DSP_.pdf)
> [Chapter 3-Discrete-Time Signals in the Frequency Domain 191008.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997116/Chapter.3-Discrete-Time.Signals.in.the.Frequency.Domain.191008.pdf)s
> [Chapter 4-Discrete Time System190310.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997117/Chapter.4-Discrete.Time.System190310.pdf)
> [Chapter 4-Discrete Time System191016.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997118/Chapter.4-Discrete.Time.System191016.pdf)
> [Chapter 5-Finite-length Discrete TransformB-191021.pdf](https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams/files/3997119/Chapter.5-Finite-length.Discrete.TransformB-191021.pdf)

非常感谢！
